db: # 数据库
  app: # 应用数据库
    host: 127.0.0.1
    port: 3306
    user: root
    password: ${oc.env:APP_DB_PASSWORD}
    database: chat
  auth: # 认证数据库
    host: 127.0.0.1
    port: 3306
    user: root
    password: ${oc.env:AUTH_DB_PASSWORD}
    database: auth

log: # 日志
  app:
    to_console: true # 是否输出到控制台
    to_console_level: INFO # 日志级别(DEBUG, INFO, WARNING, ERROR, CRITICAL)
    to_file: true # 是否输出到文件
    to_file_level: INFO # 日志级别(DEBUG, INFO, WARNING, ERROR, CRITICAL)
    log_dir: app # 日志目录
    max_file_size: 10MB # 单个日志文件最大大小
  auth:
    to_console: true # 是否输出到控制台
    to_console_level: ERROR # 日志级别(DEBUG, INFO, WARNING, ERROR, CRITICAL)
    to_file: true # 是否输出到文件
    to_file_level: INFO # 日志级别(DEBUG, INFO, WARNING, ERROR, CRITICAL)
    log_dir: auth # 日志目录
    max_file_size: 10MB # 单个日志文件最大大小

auth: # 认证配置
  secret_key: ${oc.env:AUTH_SECRET_KEY}
  algorithm: HS256
  access_token_expire_minutes: 60
  refresh_token_expire_days: 7

cos: # 腾讯云COS配置
  bucket: chat-${oc.env:COS_APP_ID}
  secret_id: ${oc.env:COS_SECRET_ID}
  secret_key: ${oc.env:COS_SECRET_KEY}
  region: ap-beijing
  token: null
  scheme: https

encryption_key: ${oc.env:ENCRYPTION_KEY}
cors_origins:
  - http://localhost:12321
port: 12321
